// <auto-generated />
namespace FarmOrder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FarmOrderEtc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FarmOrderEtc));
        
        string IMigrationMetadata.Id
        {
            get { return "201808161148480_FarmOrderEtc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
